In [3]:
phrase = "In general, I love music. But I love pop music more than any other musical genre. To me, music is my greatest  love."

In [4]:
phrase

'In general, I love music. But I love pop music more than any other musical genre. To me, music is my greatest  love.'

In [5]:
!pip install pandas nltk

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 10.5 MB/s eta 0:00:00m eta 0:00:010:01:01
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
  Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
  Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 kB 7.0 MB/s eta 0:00:000:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 785.2/785.2 kB 18.0 MB/s eta 0:00:00m eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 10.5 MB/s eta 0:00:00

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [12]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
import pandas as pd

In [8]:
ps = PorterStemmer()
words = word_tokenize(phrase)

In [10]:
words

['In',
 'general',
 ',',
 'I',
 'love',
 'music',
 '.',
 'But',
 'I',
 'love',
 'pop',
 'music',
 'more',
 'than',
 'any',
 'other',
 'musical',
 'genre',
 '.',
 'To',
 'me',
 ',',
 'music',
 'is',
 'my',
 'greatest',
 'love',
 '.']

In [11]:
stemmed = [ps.stem(w) for w in words]
stemmed

['in',
 'gener',
 ',',
 'i',
 'love',
 'music',
 '.',
 'but',
 'i',
 'love',
 'pop',
 'music',
 'more',
 'than',
 'ani',
 'other',
 'music',
 'genr',
 '.',
 'to',
 'me',
 ',',
 'music',
 'is',
 'my',
 'greatest',
 'love',
 '.']

In [16]:
import numpy as np

def build_co_occurrence_matrix(tokenized_corpus,window_size):
    #build unique words
    unique_words=set()
    for t_text in tokenized_corpus:
        for t_word in t_text:
            unique_words.add(t_word)

    word_search_dict={word:np.zeros(shape=(len(unique_words))) for word in unique_words}
    word_list=list(word_search_dict.keys())
    for t_text in tokenized_corpus:
        for idx,word in enumerate(t_text):
            #pick word in the size range
            i=max(0,idx-window_size)
            j=min(len(t_text)-1,idx+window_size)
            search=[t_text[idx_] for idx_ in range(i,j+1)]
            search.remove(word)
            for neighbor in search:
                # get neighbor idx in word_search_dict
                nei_idx=word_list.index(neighbor)
                word_search_dict[word][nei_idx]+=1
    return word_search_dict

In [28]:
coo_dict = build_co_occurrence_matrix([words], 4)

In [29]:
coo_df = pd.DataFrame(coo_dict,index=coo_dict.keys()).astype('int')
coo_df

To  my  musical  .  than  ,  pop  greatest  In  me  love  I  \
To         0   0        1  1     0  1    0         0   0   1     0  0   
my         0   0        0  1     0  1    0         1   0   1     1  0   
musical    1   0        0  1     1  0    0         0   0   1     0  0   
.          1   1        1  0     0  2    1         1   0   1     3  2   
than       0   0        1  0     0  0    1         0   0   0     1  0   
,          1   1        0  2     0  0    0         1   1   1     1  1   
pop        0   0        0  1     1  0    0         0   0   0     1  1   
greatest   0   1        0  1     0  1    0         0   0   0     1  0   
In         0   0        0  0     0  1    0         0   0   0     1  1   
me         1   1        1  1     0  1    0         0   0   0     0  0   
love       0   1        0  3     1  1    1         1   1   0     0  3   
I          0   0        0  2     0  1    1         0   1   0     3  0   
general    0   0        0  0     0  1    0         0   1   0     1  1   
is         1   1        0  1     0  1    0         1   0   1     1  0   
music      1   1        0  2     1  2    1         1   0   1     4  3   
other      1   0        1  1     1  0    0         0   0   0     0  0   
more       0   0        1  0     1  0    1         0   0   0     1  1   
But        0   0        0  1     0  0    1         0   0   0     2  2   
genre      1   0        1  1     1  1    0         0   0   1     0  0   
any        0   0        1  1     1  0    1         0   0   0     0  0   

          general  is  music  other  more  But  genre  any  
To              0   1      1      1     0    0      1    0  
my              0   1      1      0     0    0      0    0  
musical         0   0      0      1     1    0      1    1  
.               0   1      2      1     0    1      1    1  
than            0   0      1      1     1    0      1    1  
,               1   1      2      0     0    0      1    0  
pop             0   0      1      0     1    1      0    1  
greatest        0   1      1      0     0    0      0    0  
In              1   0      0      0     0    0      0    0  
me              0   1      1      0     0    0      1    0  
love            1   1      4      0     1    2      0    0  
I               1   0      3      0     1    2      0    0  
general         0   0      1      0     0    0      0    0  
is              0   0      1      0     0    0      0    0  
music           1   1      0      1     1    2      0    1  
other           0   0      1      0     1    0      1    1  
more            0   0      1      1     0    0      0    1  
But             0   0      2      0     0    0      0    0  
genre           0   0      0      1     0    0      0    1  
any             0   0      1      1     1    0      1    0

In [33]:
coo_df.loc['music']['love']

4

In [36]:
vectors_df = pd.DataFrame(
    {
        'data': np.array([6,0,0]),
        'boba': np.array([0,4,6]),
        'ice-cream': np.array([1,6,8])
    },
    index=['AI','drinks','food']
).astype('float64')
vectors_df

data  boba  ice-cream
AI       6.0   0.0        1.0
drinks   0.0   4.0        6.0
food     0.0   6.0        8.0

In [38]:
#Euclidean Distance
np.linalg.norm(vectors_df['ice-cream'] - vectors_df['boba'])

3.0

In [39]:
diff = np.linalg.norm(vectors_df['ice-cream'] - vectors_df['boba'])
sum_sq = np.dot(diff.T, diff)
np.sqrt(sum_sq)

3.0

In [45]:
history = np.array([30,20])
agriculture = np.array([20,40])

dot_prod = np.dot(history, agriculture)
dot_prod/(np.linalg.norm(history) * np.linalg.norm(agriculture))

0.8682431421244591

In [52]:
usa = np.array([5,6])
russia = np.array([5,5])
japan = np.array([4,3])
turkey = np.array([3,1])

washington = np.array([10,5])
ankara = np.array([9,1])

In [54]:
diff = usa - washington

In [55]:
country = diff + ankara
country

array([4, 2])

In [73]:
countries = np.stack((usa, russia, japan, turkey), axis=0)
countries

array([[5, 6],
       [5, 5],
       [4, 3],
       [3, 1]])

In [71]:
#cosine similarity
dot_products = np.dot(countries, country)
dot_products

array([32, 30, 22, 14])

In [72]:
norms = np.linalg.norm(countries, axis=1)
s = dot_products/(norms * np.linalg.norm(country))
s

array([0.91615733, 0.9486833 , 0.98386991, 0.98994949])

In [76]:
#euclidean siatance
diff = (countries - country)
diff

array([[ 1,  4],
       [ 1,  3],
       [ 0,  1],
       [-1, -1]])

In [77]:
d = np.linalg.norm(diff, axis=1)
d

array([4.12310563, 3.16227766, 1.        , 1.41421356])

Transforming Vectors

In [2]:
import numpy as np

R = np.array([[2,0],[0, -2]])
X = np.array([[1,1]])
np.dot(X,R)

array([[ 2, -2]])

In [3]:
A = np.array([
    [2,2,],
    [2,2]    
])
A_squared = np.square(A)
A_squared

array([[4, 4],
       [4, 4]])

In [4]:
A_Frobenious = np.sqrt(np.sum(A_squared))
A_Frobenious

4.0

In [7]:
def basic_hash_table(value_l, n_buckets):
    def hash_function(value, n_buckets):
        return int(value) % n_buckets
    hash_table = {i:[] for i in range(n_buckets)}
    for value in value_l:
        hash_value = hash_function(value, n_buckets)
        hash_table[hash_value].append(value)
    return hash_table

In [9]:
P = np.array([1,1])
V1 = np.array([1,1])
V2 = np.array([2,2])
V3 = np.array([-1,-1])

In [10]:
np.dot(np.stack((V1,V2,V3)), P)

array([ 2,  4, -2])

In [24]:
def side_of_plane(P,v):
    dotproduct = np.dot(P, v.T)
    sign_of_doct_product = np.sign(dotproduct)
    return sign_of_doct_product
    

In [18]:
side_of_plane(P,V3)

-1

In [19]:
def hash_multiple_plane(P_l, v):
    hash_value = 0
    for i, P in enumerate(P_l):
        sign = side_of_plane(P,v)
        hash_i = 1 if sign >= 0 else 0
        hash_value += 2**i * hash_i
    return hash_value
        

In [21]:
(2**0*1) + (2**1*0) + (2**2*0) + (2**3*0)

1

In [22]:
num_dimensions = 2
num_planes = 3

random_planes_matrix = np.random.normal(size=(num_planes, num_dimensions))
random_planes_matrix

array([[ 1.5695374 ,  0.54734764],
       [-0.11442444,  0.17338993],
       [ 0.58419258, -0.02446321]])

In [23]:
v = np.array([[2,2]])

In [26]:
num_planes_matrix = side_of_plane(random_planes_matrix, v)
num_planes_matrix

array([[1.],
       [1.],
       [1.]])

In [27]:
hash_multiple_plane(random_planes_matrix, v )

7

In [28]:
word_embedding = {
    "I": np.array([1,0,1]),
    "love": np.array([-1,0,1]),
    "learning": np.array([1,0,1])
}
words_in_document = ["I", "love", "learning"]
document_embedding = np.array([0,0,0])
for word in words_in_document:
    document_embedding += word_embedding.get(word,0)

In [29]:
document_embedding

array([1, 0, 3])